// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: srcjflexcup/toy3.flex

package main.java.org.example;
import java.util.HashMap;
import java_cup.runtime.Symbol;
import java.util.Collections;



// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\1\7\4\0\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\12\21\1\22\1\23\1\24"+
    "\1\25\1\26\2\0\32\27\1\0\1\30\4\0\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\2\27\1\42\1\43\1\44\1\45\1\46\1\27\1\47"+
    "\1\50\1\51\1\52\1\53\1\54\3\27\1\55\1\56"+
    "\1\57\7\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\2\1\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\21\21\1\22\1\23\1\24\2\0\1\25"+
    "\4\0\1\26\1\0\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\5\21\1\36\4\21\1\37\1\21\1\40"+
    "\2\21\1\41\6\21\1\42\1\43\2\0\2\26\1\44"+
    "\1\45\3\21\1\46\2\21\1\47\2\21\1\50\1\51"+
    "\1\3\1\21\1\52\5\21\1\0\1\26\1\21\1\53"+
    "\1\54\1\21\1\55\5\21\1\56\1\57\1\21\1\60"+
    "\1\21\1\61\1\62\3\21\1\63\1\64\1\21\1\65"+
    "\1\66\1\67";

  private static int [] zzUnpackAction() {
    int [] result = new int[134];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\140\0\140\0\220\0\300\0\360\0\u0120"+
    "\0\140\0\140\0\140\0\140\0\140\0\140\0\u0150\0\u0180"+
    "\0\u01b0\0\140\0\u01e0\0\u0210\0\u0240\0\u0270\0\u02a0\0\u02d0"+
    "\0\u0300\0\u0330\0\u0360\0\u0390\0\u03c0\0\u03f0\0\u0420\0\u0450"+
    "\0\u0480\0\u04b0\0\u04e0\0\u0510\0\u0540\0\u0570\0\140\0\140"+
    "\0\140\0\u05a0\0\360\0\140\0\u05d0\0\u0600\0\u0630\0\u0660"+
    "\0\u0690\0\u06c0\0\140\0\140\0\140\0\140\0\140\0\140"+
    "\0\140\0\u06f0\0\u0720\0\u0750\0\u0780\0\u07b0\0\u07e0\0\u0810"+
    "\0\u0840\0\u0870\0\u08a0\0\u0270\0\u08d0\0\u0270\0\u0900\0\u0930"+
    "\0\u0270\0\u0960\0\u0990\0\u09c0\0\u09f0\0\u0a20\0\u0a50\0\140"+
    "\0\140\0\u0a80\0\u0ab0\0\140\0\u0ae0\0\u06c0\0\u0270\0\u0b10"+
    "\0\u0b40\0\u0b70\0\u0270\0\u0ba0\0\u0bd0\0\u0270\0\u0c00\0\u0c30"+
    "\0\u0270\0\u0270\0\u0270\0\u0c60\0\u0270\0\u0c90\0\u0cc0\0\u0cf0"+
    "\0\u0d20\0\u0d50\0\u0d80\0\u0a80\0\u0db0\0\u0270\0\u0270\0\u0de0"+
    "\0\u0270\0\u0e10\0\u0e40\0\u0e70\0\u0ea0\0\u0ed0\0\u0270\0\u0270"+
    "\0\u0f00\0\u0270\0\u0f30\0\u0270\0\u0270\0\u0f60\0\u0f90\0\u0fc0"+
    "\0\u0270\0\u0270\0\u0ff0\0\u0270\0\u0270\0\u0270";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[134];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\3\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\3"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\26"+
    "\1\36\1\37\1\26\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\2\26\1\46\1\47\1\50\1\51\2\3\4\0"+
    "\1\3\1\7\1\10\47\3\62\0\1\4\103\0\1\52"+
    "\31\0\7\53\1\54\20\53\1\55\27\53\10\56\1\0"+
    "\17\56\1\57\27\56\13\0\1\60\4\0\1\61\56\0"+
    "\1\62\1\0\1\20\63\0\1\63\56\0\1\64\1\65"+
    "\1\66\56\0\1\67\57\0\1\70\1\71\52\0\1\26"+
    "\5\0\1\26\1\0\24\26\24\0\1\26\5\0\1\26"+
    "\1\0\13\26\1\72\10\26\24\0\1\26\5\0\1\26"+
    "\1\0\4\26\1\73\7\26\1\74\7\26\24\0\1\26"+
    "\5\0\1\26\1\0\7\26\1\75\14\26\24\0\1\26"+
    "\5\0\1\26\1\0\4\26\1\76\7\26\1\77\7\26"+
    "\24\0\1\26\5\0\1\26\1\0\11\26\1\100\1\26"+
    "\1\101\10\26\24\0\1\26\5\0\1\26\1\0\1\102"+
    "\23\26\24\0\1\26\5\0\1\26\1\0\10\26\1\103"+
    "\13\26\24\0\1\26\5\0\1\26\1\0\5\26\1\104"+
    "\5\26\1\105\3\26\1\106\4\26\24\0\1\26\5\0"+
    "\1\26\1\0\4\26\1\107\17\26\24\0\1\26\5\0"+
    "\1\26\1\0\14\26\1\110\7\26\24\0\1\26\5\0"+
    "\1\26\1\0\16\26\1\111\5\26\24\0\1\26\5\0"+
    "\1\26\1\0\16\26\1\112\5\26\24\0\1\26\5\0"+
    "\1\26\1\0\4\26\1\113\17\26\24\0\1\26\5\0"+
    "\1\26\1\0\20\26\1\114\3\26\24\0\1\26\5\0"+
    "\1\26\1\0\7\26\1\115\6\26\1\116\5\26\24\0"+
    "\1\26\5\0\1\26\1\0\7\26\1\117\14\26\31\0"+
    "\1\120\31\0\2\53\4\0\52\53\10\0\1\121\47\0"+
    "\2\56\4\0\52\56\13\122\1\123\44\122\2\61\1\124"+
    "\2\61\1\125\52\61\21\0\1\126\57\0\1\26\5\0"+
    "\1\26\1\0\3\26\1\127\20\26\24\0\1\26\5\0"+
    "\1\26\1\0\6\26\1\130\15\26\24\0\1\26\5\0"+
    "\1\26\1\0\14\26\1\131\7\26\24\0\1\26\5\0"+
    "\1\26\1\0\1\132\23\26\24\0\1\26\5\0\1\26"+
    "\1\0\5\26\1\133\16\26\24\0\1\26\5\0\1\26"+
    "\1\0\21\26\1\134\2\26\24\0\1\26\5\0\1\26"+
    "\1\0\17\26\1\135\4\26\24\0\1\26\5\0\1\26"+
    "\1\0\3\26\1\136\20\26\24\0\1\26\5\0\1\26"+
    "\1\0\11\26\1\137\12\26\24\0\1\26\5\0\1\26"+
    "\1\0\22\26\1\140\1\26\24\0\1\26\5\0\1\26"+
    "\1\0\20\26\1\141\3\26\24\0\1\26\5\0\1\26"+
    "\1\0\20\26\1\142\3\26\24\0\1\26\5\0\1\26"+
    "\1\0\20\26\1\143\3\26\24\0\1\26\5\0\1\26"+
    "\1\0\14\26\1\144\7\26\24\0\1\26\5\0\1\26"+
    "\1\0\5\26\1\145\12\26\1\146\3\26\24\0\1\26"+
    "\5\0\1\26\1\0\16\26\1\147\5\26\24\0\1\26"+
    "\5\0\1\26\1\0\4\26\1\150\17\26\24\0\1\26"+
    "\5\0\1\26\1\0\21\26\1\151\2\26\24\0\1\26"+
    "\5\0\1\26\1\0\10\26\1\152\13\26\3\0\13\122"+
    "\1\153\57\122\1\153\4\122\1\154\37\122\2\0\1\124"+
    "\76\0\1\26\5\0\1\26\1\0\10\26\1\155\13\26"+
    "\24\0\1\26\5\0\1\26\1\0\11\26\1\156\12\26"+
    "\24\0\1\26\5\0\1\26\1\0\16\26\1\157\5\26"+
    "\24\0\1\26\5\0\1\26\1\0\1\26\1\160\22\26"+
    "\24\0\1\26\5\0\1\26\1\0\4\26\1\161\17\26"+
    "\24\0\1\26\5\0\1\26\1\0\17\26\1\162\4\26"+
    "\24\0\1\26\5\0\1\26\1\0\4\26\1\163\17\26"+
    "\24\0\1\26\5\0\1\26\1\0\6\26\1\164\15\26"+
    "\24\0\1\26\5\0\1\26\1\0\21\26\1\165\2\26"+
    "\24\0\1\26\5\0\1\26\1\0\10\26\1\166\13\26"+
    "\24\0\1\26\5\0\1\26\1\0\13\26\1\167\10\26"+
    "\24\0\1\26\5\0\1\26\1\0\4\26\1\170\17\26"+
    "\24\0\1\26\5\0\1\26\1\0\11\26\1\171\12\26"+
    "\3\0\13\122\1\153\4\122\1\124\37\122\21\0\1\26"+
    "\5\0\1\26\1\0\13\26\1\172\10\26\24\0\1\26"+
    "\5\0\1\26\1\0\11\26\1\173\12\26\24\0\1\26"+
    "\5\0\1\26\1\0\4\26\1\174\17\26\24\0\1\26"+
    "\5\0\1\26\1\0\13\26\1\175\10\26\24\0\1\26"+
    "\5\0\1\26\1\0\16\26\1\176\5\26\24\0\1\26"+
    "\5\0\1\26\1\0\16\26\1\177\5\26\24\0\1\26"+
    "\5\0\1\26\1\0\13\26\1\200\10\26\24\0\1\26"+
    "\5\0\1\26\1\0\4\26\1\201\17\26\24\0\1\26"+
    "\5\0\1\26\1\0\4\26\1\202\17\26\24\0\1\26"+
    "\5\0\1\26\1\0\1\203\23\26\24\0\1\26\5\0"+
    "\1\26\1\0\13\26\1\204\10\26\24\0\1\26\5\0"+
    "\1\26\1\0\6\26\1\205\15\26\24\0\1\26\5\0"+
    "\1\26\1\0\12\26\1\206\11\26\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4128];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\4\1\6\11\3\1\1\11\24\1\3\11"+
    "\2\0\1\11\4\0\1\1\1\0\7\11\26\1\2\11"+
    "\2\0\1\11\26\1\1\0\33\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[134];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    StringBuffer string = new StringBuffer();
        private Symbol symbol(int type) {
            Symbol s = new Symbol(type, yyline, yycolumn);
            //System.out.println("Token: " + sym.terminalNames[type] );
            return s;
        }
        private Symbol symbol(int type, Object value) {
            //System.out.println("Token: " + sym.terminalNames[type] + ", Value: " + value.toString());
            return new Symbol(type, yyline, yycolumn, value);
        }

        // Tabella degli identificatori (stringhe)
        public static HashMap<String, String> stringTable = new HashMap<>();

        private Symbol installID(String value) {
            if(!stringTable.containsKey(value)) {
                stringTable.put(value, value);
            }
            return symbol(sym.ID, value);
        }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return symbol(sym.error, "Error at char: " + yytext() + " in line: " + (yyline + 1) + " and column: " + (yycolumn + 1));
            }
            // fall through
          case 56: break;
          case 2:
            { /* Ignora spazi bianchi */
            }
            // fall through
          case 57: break;
          case 3:
            { return symbol(sym.NOT);
            }
            // fall through
          case 58: break;
          case 4:
            { return symbol(sym.LPAR);
            }
            // fall through
          case 59: break;
          case 5:
            { return symbol(sym.RPAR);
            }
            // fall through
          case 60: break;
          case 6:
            { return symbol(sym.TIMES);
            }
            // fall through
          case 61: break;
          case 7:
            { return symbol(sym.PLUS);
            }
            // fall through
          case 62: break;
          case 8:
            { return symbol(sym.COMMA);
            }
            // fall through
          case 63: break;
          case 9:
            { return symbol(sym.MINUS);
            }
            // fall through
          case 64: break;
          case 10:
            { return symbol(sym.DIV);
            }
            // fall through
          case 65: break;
          case 11:
            { return symbol(sym.INT_CONST, yytext());
            }
            // fall through
          case 66: break;
          case 12:
            { return symbol(sym.COLON);
            }
            // fall through
          case 67: break;
          case 13:
            { return symbol(sym.SEMI);
            }
            // fall through
          case 68: break;
          case 14:
            { return symbol(sym.LT);
            }
            // fall through
          case 69: break;
          case 15:
            { return symbol(sym.ASSIGNDECL);
            }
            // fall through
          case 70: break;
          case 16:
            { return symbol(sym.GT);
            }
            // fall through
          case 71: break;
          case 17:
            { return installID(yytext());
            }
            // fall through
          case 72: break;
          case 18:
            { return symbol(sym.LBRAC);
            }
            // fall through
          case 73: break;
          case 19:
            { return symbol(sym.PIPE);
            }
            // fall through
          case 74: break;
          case 20:
            { return symbol(sym.RBRAC);
            }
            // fall through
          case 75: break;
          case 21:
            { return symbol(sym.STRING_CONST, yytext());
            }
            // fall through
          case 76: break;
          case 22:
            { /* Ignora commenti */
            }
            // fall through
          case 77: break;
          case 23:
            { return symbol(sym.ASSIGN);
            }
            // fall through
          case 78: break;
          case 24:
            { return symbol(sym.IN);
            }
            // fall through
          case 79: break;
          case 25:
            { return symbol(sym.LE);
            }
            // fall through
          case 80: break;
          case 26:
            { return symbol(sym.NE);
            }
            // fall through
          case 81: break;
          case 27:
            { return symbol(sym.EQ);
            }
            // fall through
          case 82: break;
          case 28:
            { return symbol(sym.GE);
            }
            // fall through
          case 83: break;
          case 29:
            { return symbol(sym.OUT);
            }
            // fall through
          case 84: break;
          case 30:
            { return symbol(sym.DO);
            }
            // fall through
          case 85: break;
          case 31:
            { return symbol(sym.IF);
            }
            // fall through
          case 86: break;
          case 32:
            { return symbol(sym.IS);
            }
            // fall through
          case 87: break;
          case 33:
            { return symbol(sym.OR);
            }
            // fall through
          case 88: break;
          case 34:
            { return symbol(sym.OUTNL);
            }
            // fall through
          case 89: break;
          case 35:
            { return symbol(sym.CHAR_CONST, yytext());
            }
            // fall through
          case 90: break;
          case 36:
            { return symbol(sym.DOUBLE_CONST, yytext());
            }
            // fall through
          case 91: break;
          case 37:
            { return symbol(sym.AND);
            }
            // fall through
          case 92: break;
          case 38:
            { return symbol(sym.DEF);
            }
            // fall through
          case 93: break;
          case 39:
            { return symbol(sym.END);
            }
            // fall through
          case 94: break;
          case 40:
            { return symbol(sym.INT);
            }
            // fall through
          case 95: break;
          case 41:
            { return symbol(sym.LET);
            }
            // fall through
          case 96: break;
          case 42:
            { return symbol(sym.REF);
            }
            // fall through
          case 97: break;
          case 43:
            { return symbol(sym.BOOL);
            }
            // fall through
          case 98: break;
          case 44:
            { return symbol(sym.CHAR);
            }
            // fall through
          case 99: break;
          case 45:
            { return symbol(sym.ELSE);
            }
            // fall through
          case 100: break;
          case 46:
            { return symbol(sym.THEN);
            }
            // fall through
          case 101: break;
          case 47:
            { return symbol(sym.TRUE);
            }
            // fall through
          case 102: break;
          case 48:
            { return symbol(sym.BEGIN);
            }
            // fall through
          case 103: break;
          case 49:
            { return symbol(sym.FALSE);
            }
            // fall through
          case 104: break;
          case 50:
            { return symbol(sym.GIVEN);
            }
            // fall through
          case 105: break;
          case 51:
            { return symbol(sym.WHILE);
            }
            // fall through
          case 106: break;
          case 52:
            { return symbol(sym.DOUBLE);
            }
            // fall through
          case 107: break;
          case 53:
            { return symbol(sym.RETURN);
            }
            // fall through
          case 108: break;
          case 54:
            { return symbol(sym.STRING);
            }
            // fall through
          case 109: break;
          case 55:
            { return symbol(sym.PROGRAM);
            }
            // fall through
          case 110: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
